### ISSUE TITLE
Move project to easy to include hpp file

### ISSUE THREAD

**Issue by RedMoon32** [RedMoon32/ShabeFramework#11]
Move everything to one .hpp file
Maybe find some tool (which will help to automate the process) or do it by yourself
There is not so much work, just move to one file and resolve different 'include' issues
As a result https://github.com/RedMoon32/ShabeFramework/blob/master/examples/main.c must work with just 
one 'shabe.hpp' included

**Comment by everlearner** [comment]
So, you want all header files to be included in one shabe.hpp ? Pls clarify
